### PR TITLE
Fix/make test #65

### LINKED ISSUE #65: `make test-playground` fails
Here is the result of the Jest testing:

```
 FAIL  __tests__/Editor.test.tsx
  ● Test suite failed to run

    src/components/WasmTest/Wasm.tsx:7:44 - error TS1343: The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'esnext', or 'system'.

    7     new Worker(new URL('./wasm.worker.ts', import.meta.url), {
                                                 ~~~~~~~~~~~

 FAIL  __tests__/Welcome.test.tsx
  ● Test suite failed to run

    src/components/WasmTest/Wasm.tsx:7:44 - error TS1343: The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'esnext', or 'system'.

    7     new Worker(new URL('./wasm.worker.ts', import.meta.url), {
                                                 ~~~~~~~~~~~

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        63.12 s, estimated 90 s
```

### PR DESCRIPTION
**Pull request by thought2**
closes #65

- `make playground-test` fails because `yarn workspace playground test` fails. A `git bisect` turned out that this was introduced by commit 07ed0e0935c1253f7fe937b79801e7dc36f08706 . It's the `re-export` in `components/index.ts` that causes the error. Which is surprising. However, the main problem is that Jest seems to have problems with `import.meta` as [mentioned here](https://stackoverflow.com/questions/64961387/how-to-use-import-meta-when-testing-with-jest).
One suggested fix is to set `target` and `module` to `esnext` in the `tsconfig.ts`. We can do this safely as we're using `babel` and not `tsc` for transpiling. Other solutions seem to be more hacky, that's why I chose this approach.

- by this occasion I realized, that currently CI does not run the playground test. That's why I introduced a `playground.yml` file to GitHub actions (in analogy to the structure in the make file).

### CODE REVIEW

**Review by nmauersberg — APPROVED** [review]
Cool, thank you for your research on this.
